plugin_name: vault
version: "{{ lookup('file', playbook_dir + '/../VERSION') }}"
build_dir: "{{ playbook_dir }}/../build"
plugin_binary: "{{ build_dir }}/vault-linux-amd64"
plugin_dir: "/usr/local/emhttp/plugins/{{ plugin_name }}"
config_dir: "/boot/config/plugins/{{ plugin_name }}"
binary_path: "/usr/local/sbin/vault"
rc_script: "/etc/rc.d/rc.vault"
api_port: "{{ hostvars[inventory_hostname].api_port | default(24085) }}"
bind_address: "{{ hostvars[inventory_hostname].bind_address | default('127.0.0.1') }}"
verify_local_port: "{{ hostvars[inventory_hostname].verify_local_port | default(42485) }}"
db_path: "{{ config_dir }}/vault.db"
log_path: "/var/log/vault.log"
pid_file: "/var/run/vault.pid"
create_backup: false

# Vault Replica container
replica_port: "{{ hostvars[inventory_hostname].replica_port | default(24086) }}"
replica_data_dir: /mnt/cache/appdata/vault-replica
replica_storage_dir: /mnt/user/backups/vault-replica
timezone: Australia/Sydney
