name: Close Stale Issues

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to inactivity. If no further activity occurs, it will be closed in 7 days (14 days total inactivity)."
          days-before-issue-stale: 7 # Number of days before an issue becomes stale
          days-before-issue-close: 7 # Number of days to wait after marking as stale before closing
          days-before-pr-stale: -1 # Disable stale handling for pull requests
          days-before-pr-close: -1 # Disable auto-closing pull requests
          exempt-issue-labels: "pinned,enhancement,status: blocked" # Do not mark issues with these labels as stale
          operations-per-run: 30 # Number of actions to perform per run
